# A simple example of ClusterConfig object:
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: roboshop
  region: us-east-1

managedNodeGroups:
- name: spot
  # instanceType: m5.large
  instanceType: t3.medium   
  desiredCapacity: 3
  spot: true